
name: Single html generator

on:
  workflow_call:
    inputs:
      key:
        required: true
        type: string

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create directory
        run: |
          echo Before
          ls -la
          mkdir ${{ inputs.key }}
          echo AFTER
          ls -la

      - name: Create html file
        run: |
          echo Hello hello world > ${{ inputs.key }}/index.html
          echo AFTER FILE ADDED
          ls
          ls -la ${{ inputs.key }}
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ inputs.key }}
          path: "./${{ inputs.key }}"
