
name: Single html generator

on:
  workflow_call:
    inputs:
      key:
        required: true
        type: string

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create directory
        run: |
          mkdir ${{ inputs.key }}

      - name: Create html file
        run: |
          echo Hello ${{ inputs.key }} world OwO > ${{ inputs.key }}/index.html
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ inputs.key }}
          path: "./${{ inputs.key }}"
