
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: |
          mkdir test1
          mkdir test2
          mkdir test3

      - name: Create html files
        run: |
          echo Hello world > test1/index.html
          echo Another world > test2/index.html
          echo Yet another world > test3/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3
  
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./"

  deploy-tests:
      runs-on: ubuntu-latest
      needs: build-html
      
      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4