name: Vue e2e tests

on:
  workflow_dispatch:

jobs:
  run-all-e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        specs: [
          { key: 'desktop' },
          { key: 'mobile' },
        ]
    uses: ./.github/workflows/testYaml.yml
    with:
      key: ${{ matrix.specs.key }}
    secrets: inherit