
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create html
        run: echo Hello world > test/index.html

      - name: Create more html files
        run: |
          echo Another world > test2/index.html
          echo Yet another world > test3/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3
  
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1

  deploy-tests:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: build-html
      
      permissions:
        pages: write
        id-token: write

      environment:
        # environment created automatically by GitHub
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4