name: Parallel deploy test

on:
  workflow_dispatch:

jobs:
  run-many-deployments:
    permissions:
        pages: write
        id-token: write
        actions: read

    strategy:
      fail-fast: false
      matrix:
        specs: [
          { key: 'desktop' },
          { key: 'mobile' },
        ]
    uses: ./.github/workflows/testYaml.yml
    with:
      key: ${{ matrix.specs.key }}
    secrets: inherit